/**
 * @file ws281x.c
 * @brief Implementation of the WS281x addressable LED driver.
 *
 * @author Leo Walker
 */

#include <stdlib.h>
#include <math.h>

#include "ws281x.h"
#include "hardware/pio.h"

#pragma region PIO Program
// -------------------------------------------------- //
// This code is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

// ------ //
// ws281x //
// ------ //

#define WS281X_WRAP_TARGET 0
#define WS281X_WRAP 3

#define WS281X_T1 2
#define WS281X_T2 5
#define WS281X_T3 3

static const uint16_t ws281x_program_instructions[] = {
    //     .wrap_target
    0x6221, //  0: out    x, 1            side 0 [2]
    0x1123, //  1: jmp    !x, 3           side 1 [1]
    0x1400, //  2: jmp    0               side 1 [4]
    0xa442, //  3: nop                    side 0 [4]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ws281x_program = {
    .instructions = ws281x_program_instructions,
    .length = 4,
    .origin = -1,
};

static inline pio_sm_config ws281x_program_get_default_config(uint offset)
{
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + WS281X_WRAP_TARGET, offset + WS281X_WRAP);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

#include "hardware/clocks.h"
static inline void ws281x_program_init(PIO pio, uint sm, uint offset, uint pin, float freq, bool rgbw)
{
    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    pio_sm_config c = ws281x_program_get_default_config(offset);
    sm_config_set_sideset_pins(&c, pin);
    sm_config_set_out_shift(&c, false, true, rgbw ? 32 : 24);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
    int cycles_per_bit = WS281X_T1 + WS281X_T2 + WS281X_T3;
    float div = clock_get_hz(clk_sys) / (freq * cycles_per_bit);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

static inline void ws281x_deinit(PIO pio, uint sm, uint pin)
{
    gpio_deinit(pin);
    pio_sm_set_enabled(pio, sm, false);
    pio_sm_clear_fifos(pio, sm);
}

#endif
// -------------------------------------------------- //
#pragma endregion

struct ws281x_impl
{
    ws281x_config_t config;
    PIO hardware_instance;
    int program_offset;

    colour_t *led_buffer;
};

WS281X ws281x_init(ws281x_config_t *config)
{
    // Is config null?
    if (!config)
        return NULL;

    // Allocate memory for instance.
    struct ws281x_impl *dev = malloc(sizeof(struct ws281x_impl));
    if (!dev)
        return NULL;

    // Copy config to instance.
    dev->config = *config;

    // Map hardware enum to PIO hardware blocks.
    switch (dev->config.hardware_block)
    {
    case WS281X_PIO_0:
        dev->hardware_instance = pio0;
        break;

    case WS281X_PIO_1:
        dev->hardware_instance = pio1;
        break;

    case WS281X_PIO_2:
        dev->hardware_instance = pio2;
        break;
    }

    // Allocate buffer for led colours.
    dev->led_buffer = malloc(sizeof(colour_t) * dev->config.led_count);
    if (!dev->led_buffer)
    {
        free(dev);
        return NULL;
    }

    //  Load WS281x driver program into PIO.
    dev->program_offset = pio_add_program(dev->hardware_instance, &ws281x_program);

    // Init PIO blocks
    ws281x_program_init(dev->hardware_instance, dev->config.state_machine, dev->program_offset, dev->config.gpio_pin, 1000000, false);

    return dev;
}

void ws281x_destroy(WS281X dev)
{
    if (!dev)
        return;

    ws281x_deinit(dev->hardware_instance, dev->config.state_machine, dev->config.gpio_pin);

    pio_remove_program(dev->hardware_instance, &ws281x_program, dev->program_offset);

    if (dev->led_buffer)
        free(dev->led_buffer);
    free(dev);
}

void ws281x_update(WS281X dev)
{
    for (int i = 0; i < dev->config.led_count; i++)
    {
        while (pio_sm_is_tx_fifo_full(dev->hardware_instance, dev->config.state_machine))
        {
        }
        uint32_t value = ((uint32_t)(dev->led_buffer[i].b) << 8) | ((uint32_t)(dev->led_buffer[i].r) << 16) | ((uint32_t)(dev->led_buffer[i].g) << 24) | (uint32_t)(0);
        pio_sm_put(dev->hardware_instance, dev->config.state_machine, value);
    }
}

void ws281x_set_led(WS281X dev, uint16_t led_offset, const colour_t colour)
{
    led_offset %= dev->config.led_count;
    dev->led_buffer[led_offset] = colour;
}

void ws281x_set_all(WS281X dev, const colour_t colour)
{
    for (int i = 0; i < dev->config.led_count; i++)
    {
        dev->led_buffer[i] = colour;
    }
}
